services:
  postgres:
    image: postgres:latest
    container_name: gscores-postgres
    environment:
      POSTGRES_DB: gscores_db
      POSTGRES_USER: gscores
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - gscores-network

volumes:
  postgres_data:

networks:
  gscores-network:
